// Generated by CoffeeScript 1.3.3
(function() {
  var Canvas;

  P.Canvas = {};

  Canvas = (function() {

    function Canvas(canvasId, width, height) {
      this.element = document.getElementById(canvasId);
      this.element.width = width;
      this.element.height = height;
      this.context = this.element.getContext('2d');
      this.centerX = width / 2;
      this.centerY = height / 2;
    }

    Canvas.prototype.clear = function() {
      return this.element.width = this.element.width;
    };

    Canvas.prototype.drawRandomCircle = function() {
      var x, y;
      x = Math.floor(Math.random() * (this.element.width - 0 + 1)) + 0;
      y = Math.floor(Math.random() * (this.element.height - 0 + 1)) + 0;
      this.context.beginPath();
      this.context.arc(x, y, 10, 0, 2 * Math.PI, false);
      this.context.fillStyle = "rgb(255, 0, 0)";
      return this.context.fill();
    };

    return Canvas;

  })();

  P.Canvas = Canvas;

}).call(this);
