// Generated by CoffeeScript 1.3.3
(function() {
  var Canvas;

  P.Canvas = {};

  Canvas = (function() {

    function Canvas(canvasId, width, height) {
      this.element = document.getElementById(canvasId);
      this.element.width = width;
      this.element.height = height;
      this.context = this.element.getContext('2d');
      this.centerX = width / 2;
      this.centerY = height / 2;
    }

    Canvas.prototype.clear = function() {
      return this.element.width = this.element.width;
    };

    Canvas.prototype.drawRandomCircle = function() {
      var x, y;
      x = P.Util.randomInRange(0, this.element.width);
      y = P.Util.randomInRange(0, this.element.height);
      this.context.beginPath();
      this.context.arc(x, y, 10, 0, 2 * Math.PI, false);
      this.context.fillStyle = "rgb(255, 0, 0)";
      return this.context.fill();
    };

    Canvas.prototype.displayStats = function() {
      this.context.fillStyle = "Black";
      this.context.font = "normal 14pt Arial";
      return this.context.fillText(P.scene.fps + " fps", 10, 26);
    };

    return Canvas;

  })();

  P.Canvas = Canvas;

}).call(this);
