// Generated by CoffeeScript 1.3.3
(function() {
  var Core;

  Core = {
    start: function(canvasId, width, height, gameClass) {
      var couldntLoad, game, loader;
      P.canvas = new P.Canvas(canvasId, width, height);
      game = new gameClass();
      loader = new P.Loader(game);
      couldntLoad = loader._load();
      if (!couldntLoad) {
        return game.run();
      } else {
        return console.log('oops');
      }
    }
  };

  P.start = Core.start;

}).call(this);
