// Generated by CoffeeScript 1.3.3
(function() {
  var Core;

  Core = {
    start: function(canvasId, width, height, sceneClass) {
      var couldntLoad, loader, scene, time;
      window.requestAnimFrame = (function() {
        return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(callback, element) {
          return window.setTimeout(callback(+(new Date), 1000 / 60));
        };
      })();
      P.canvas = new P.Canvas(canvasId, width, height);
      P.input = new P.Input();
      P.detect = new P.Detector();
      scene = new sceneClass();
      loader = new P.Loader(scene);
      couldntLoad = loader._load();
      return time = setInterval(function() {
        if (loader.finished) {
          clearInterval(time);
          P.scene = scene;
          if (!couldntLoad) {
            P.canvas.clear();
            return P.scene.run();
          } else {
            console.log(couldntLoad);
            return console.log('oops');
          }
        }
      }, 1000);
    }
  };

  P.start = Core.start;

}).call(this);
