// Generated by CoffeeScript 1.3.3
(function() {
  var Core;

  Core = {
    start: function(canvasId, width, height, sceneClass) {
      var couldntLoad, loader, scene;
      P.canvas = new P.Canvas(canvasId, width, height);
      P.detect = new P.Detector();
      scene = new sceneClass();
      loader = new P.Loader(scene);
      couldntLoad = loader._load();
      loader.sounds["song"].play();
      window.requestAnimFrame = (function() {
        return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(callback, element) {
          return window.setTimeout(callback, 1000 / 60);
        };
      })();
      if (!couldntLoad) {
        P.canvas.clear();
        return scene.run();
      } else {
        console.log(couldntLoad);
        return console.log('oops');
      }
    }
  };

  P.start = Core.start;

}).call(this);
