// Generated by CoffeeScript 1.3.3
(function() {
  var Game;

  P.Game = {};

  Game = (function() {

    function Game() {}

    Game.prototype.run = function() {
      this.update();
      return this.draw();
    };

    Game.prototype.update = function() {};

    Game.prototype.draw = function() {};

    return Game;

  })();

  P.Game = Game;

}).call(this);
