// Generated by CoffeeScript 1.3.3
(function() {
  var P, original_P, root;

  root = this;

  original_P = root.P;

  P = void 0;

  if (typeof exports !== "undefined") {
    P = exports;
  } else {
    P = original_P = {};
    P.components = {};
    P.systems = {};
    P.my = {};
    P.Artemis = root.Artemis;
    root.P = P;
  }

  P.VERSION = "0.0.1";

}).call(this);
