// Generated by CoffeeScript 1.3.3
(function() {
  var Scene,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  P.Scene = {};

  Scene = (function() {

    function Scene() {
      this.run = __bind(this.run, this);
      this.fps = 0;
      this.displayStats = false;
      this.lastRun = null;
      this.world = new P.Artemis.EntityWorld();
    }

    Scene.prototype.update = function() {
      this.world.loopStart();
      return this.world.systemManager.updateSynchronous("update");
    };

    Scene.prototype.draw = function() {
      return this.world.systemManager.updateSynchronous("draw");
    };

    Scene.prototype.run = function() {
      if (!this.lastRun) {
        this.lastRun = new Date().getTime();
        requestAnimFrame(this.run);
        return;
      }
      this.world.delta = (new Date().getTime() - this.lastRun) / 1000;
      this.lastRun = new Date().getTime();
      this.fps = P.Util.round(1 / this.world.delta);
      P.canvas.clear();
      this.update();
      this.draw();
      P.input.clearInput();
      if (this.displayStats) {
        P.canvas.displayStats();
      }
      return requestAnimFrame(this.run);
    };

    return Scene;

  })();

  P.Scene = Scene;

}).call(this);
