// Generated by CoffeeScript 1.3.3
(function() {
  var Scene,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  P.Scene = {};

  Scene = (function() {

    function Scene() {
      this.run = __bind(this.run, this);

    }

    Scene.prototype.update = function() {};

    Scene.prototype.draw = function() {};

    Scene.prototype.run = function() {
      requestAnimFrame(this.run);
      this.update();
      return this.draw();
    };

    return Scene;

  })();

  P.Scene = Scene;

}).call(this);
