// Generated by CoffeeScript 1.3.3
(function() {
  var Util;

  P.Util = {};

  Util = {
    addEventHandling: function(destination) {
      destination.on = P.Events.addEventListener;
      destination.off = P.Events.removeEventListener;
      destination.fire = P.Events.fireEvent;
      return destination.hasEventListeners = P.Events.hasEventListeners;
    }
  };

  P.Util = Util;

}).call(this);
