// Generated by CoffeeScript 1.3.3
(function() {
  var Music,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  P.components.Music = {};

  Music = (function(_super) {

    __extends(Music, _super);

    function Music(name) {
      this.name = name;
    }

    return Music;

  })(P.Artemis.Component);

  P.components.Music = Music;

}).call(this);
