// Generated by CoffeeScript 1.3.3
(function() {
  var Position,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  P.components.Position = {};

  Position = (function(_super) {

    __extends(Position, _super);

    function Position(x, y) {
      this.x = x;
      this.y = y;
    }

    return Position;

  })(P.Artemis.Component);

  P.components.Position = Position;

}).call(this);
