// Generated by CoffeeScript 1.3.3
(function() {
  var Sound,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  P.components.Sound = {};

  Sound = (function(_super) {

    __extends(Sound, _super);

    function Sound(name) {
      this.name = name;
    }

    return Sound;

  })(P.Artemis.Component);

  P.components.Sound = Sound;

}).call(this);
