// Generated by CoffeeScript 1.3.3
(function() {
  var Sprite,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  P.components.Sprite = {};

  Sprite = (function(_super) {

    __extends(Sprite, _super);

    function Sprite(spritesheetName, spritesheetSizeX, spritesheetSizeY) {
      this.spritesheetName = spritesheetName;
      this.spritesheetSizeX = spritesheetSizeX;
      this.spritesheetSizeY = spritesheetSizeY;
      this.animations = {};
      this.currentAnim = "";
      this._currentFrame = 0;
      this._timeSinceLastUpdate = 0;
    }

    Sprite.prototype.addAnimation = function(name, frameTime, startFrame, endFrame) {
      return this.animations[name] = {
        frameTime: frameTime,
        start: startFrame,
        end: endFrame,
        length: endFrame - startFrame
      };
    };

    return Sprite;

  })(P.Artemis.Component);

  P.components.Sprite = Sprite;

}).call(this);
